In [9]:
import tensorflow.compat.v2 as tfc
import tensorflow as tf

import pathlib
import numpy as np
import pandas as pd
import IPython.display as display

tf.compat.v1.enable_eager_execution()

In [10]:
def _parse_image_function(example_proto):
    return tf.io.parse_single_example(example_proto, image_feature_description)

In [ ]:
def decode_image(raw_img):
    img = tf.image.decode_jpeg(raw_img, channels=3)
    img = tf.cast(img, tf.float32)
    return img

In [11]:
data_dir = pathlib.Path('../../datasets/celeba')
img_dir = pathlib.Path(str(data_dir) + '/img_align_celeba_png')
attr_dir = pathlib.Path(str(data_dir) + '/attr_celeba.csv')

In [17]:
df = pd.read_csv(attr_dir)
df.loc[df['Eyeglasses'] == 1]

filename  5_o_Clock_Shadow  Arched_Eyebrows  Attractive  \
52      000053.png                 1               -1          -1   
92      000093.png                -1               -1          -1   
118     000119.png                -1               -1          -1   
143     000144.png                -1               -1          -1   
151     000152.png                -1               -1          -1   
...            ...               ...              ...         ...   
202540  202541.png                -1               -1          -1   
202567  202568.png                -1               -1          -1   
202587  202588.png                -1               -1          -1   
202589  202590.png                -1               -1          -1   
202596  202597.png                -1               -1          -1   

        Bags_Under_Eyes  Bald  Bangs  Big_Lips  Big_Nose  Black_Hair  ...  \
52                   -1    -1      1        -1         1          -1  ...   
92                   -1    -1      1         1        -1          -1  ...   
118                  -1    -1     -1        -1        -1          -1  ...   
143                  -1    -1     -1        -1        -1           1  ...   
151                  -1    -1     -1        -1        -1          -1  ...   
...                 ...   ...    ...       ...       ...         ...  ...   
202540               -1    -1      1        -1        -1          -1  ...   
202567               -1    -1     -1        -1         1          -1  ...   
202587               -1    -1     -1         1         1           1  ...   
202589               -1    -1     -1        -1         1          -1  ...   
202596               -1    -1     -1        -1        -1           1  ...   

        Sideburns  Smiling  Straight_Hair  Wavy_Hair  Wearing_Earrings  \
52             -1       -1             -1         -1                -1   
92             -1       -1              1         -1                -1   
118             1       -1             -1          1                -1   
143            -1       -1             -1          1                -1   
151            -1        1              1         -1                -1   
...           ...      ...            ...        ...               ...   
202540         -1        1             -1          1                -1   
202567         -1       -1              1         -1                -1   
202587         -1       -1             -1         -1                -1   
202589         -1       -1             -1         -1                -1   
202596         -1        1             -1         -1                -1   

        Wearing_Hat  Wearing_Lipstick  Wearing_Necklace  Wearing_Necktie  \
52               -1                -1                -1               -1   
92               -1                -1                 1               -1   
118              -1                -1                -1               -1   
143              -1                -1                -1               -1   
151              -1                -1                -1                1   
...             ...               ...               ...              ...   
202540           -1                -1                -1               -1   
202567           -1                -1                -1                1   
202587           -1                -1                -1                1   
202589           -1                -1                -1               -1   
202596           -1                -1                -1               -1   

        Young   
52          -1  
92           1  
118         -1  
143         -1  
151          1  
...        ...  
202540       1  
202567      -1  
202587       1  
202589      -1  
202596       1  

[13193 rows x 41 columns]

In [22]:
raw_image_dataset = tf.data.TFRecordDataset('images.tfrecords')
raw_image_dataset

<TFRecordDatasetV1 shapes: (), types: tf.string>

In [14]:
image_feature_description = {
    'height': tf.io.FixedLenFeature([], tf.int64),
    'width': tf.io.FixedLenFeature([], tf.int64),
    'depth': tf.io.FixedLenFeature([], tf.int64),
    'raw': tf.io.FixedLenFeature([], tf.string),
}

for col in df.columns:
    if col == 'filename':
        image_feature_description[col] = tf.io.FixedLenFeature([], tf.string)
    else:
        image_feature_description[col] = tf.io.FixedLenFeature([], tf.int64)

In [15]:
parsed_image_dataset = raw_image_dataset.map(_parse_image_function)

In [26]:

for image_features in parsed_image_dataset:
    

tf.Tensor(
[[[100  97  80]
  [100  97  80]
  [100  97  80]
  ...
  [221 210 199]
  [192 184 173]
  [158 151 140]]

 [[121 118 101]
  [121 118 101]
  [121 118 101]
  ...
  [213 203 192]
  [181 174 163]
  [147 141 131]]

 [[133 130 113]
  [133 130 113]
  [133 130 113]
  ...
  [203 194 183]
  [170 163 152]
  [136 131 122]]

 ...

 [[ 42  32  30]
  [ 42  32  30]
  [ 42  32  30]
  ...
  [ 36  31  27]
  [ 36  31  27]
  [ 36  31  27]]

 [[ 41  31  29]
  [ 41  31  29]
  [ 42  32  30]
  ...
  [ 37  32  28]
  [ 37  32  28]
  [ 37  32  28]]

 [[ 39  29  27]
  [ 41  31  29]
  [ 40  30  28]
  ...
  [ 41  36  32]
  [ 41  36  32]
  [ 37  32  28]]], shape=(218, 178, 3), dtype=uint8)
